from __future__ import annotations

import json
import os

import numpy as np
import pandas as pd

from scanner.config import ROOT


BIN_SPECS = {
    "RVOL20": [-np.inf, 1.2, 1.5, 2.0, 3.0, np.inf],
    "BreakoutATR": [-np.inf, 0.25, 0.5, 1.0, 1.5, 2.0, np.inf],
    "ATRCompression": [-np.inf, 0.0, 0.15, 0.25, 0.35, np.inf],
    "Trend20": [-np.inf, -1.0, 0.0, 1.0, 2.0, np.inf],
    "Trend50": [-np.inf, -1.0, 0.0, 1.0, 2.0, np.inf],
    "Trend200": [-np.inf, -1.0, 0.0, 1.0, 2.0, np.inf],
    "RS_SPY_20": [-np.inf, -0.05, 0.0, 0.05, 0.10, np.inf],
    "TR_ATR20": [-np.inf, 1.0, 1.5, 2.0, 3.0, np.inf],
    "CloseLocation": [-np.inf, 0.35, 0.5, 0.65, 0.8, np.inf],
    "BaseRangePct": [-np.inf, 0.04, 0.06, 0.08, 0.10, 0.12, np.inf],
    "ATR20Pct": [-np.inf, 0.01, 0.02, 0.04, 0.06, 0.10, np.inf],
    "RiskATR": [-np.inf, 0.50, 0.75, 1.00, 1.25, 1.50, np.inf],
    "GapPct": [-np.inf, -0.05, -0.02, 0.0, 0.02, 0.05, np.inf],
}

TARGETS = [0.50, 0.75, 1.00, 1.25, 1.50, 2.00]
HORIZONS = [3, 5, 10]
MIN_VALIDATION_N = 100


def split_by_date(d: pd.DataFrame):
    d = d.copy()
    d["SignalDate"] = pd.to_datetime(d["SignalDate"], errors="coerce")
    d = d.dropna(subset=["SignalDate"]).sort_values("SignalDate")
    dates = pd.Series(d["SignalDate"].drop_duplicates().tolist())
    train_end = dates.iloc[int(len(dates) * 0.60)]
    valid_end = dates.iloc[int(len(dates) * 0.75)]
    train = d[d["SignalDate"] < train_end].copy()
    valid = d[(d["SignalDate"] >= train_end) & (d["SignalDate"] < valid_end)].copy()
    holdout = d[d["SignalDate"] >= valid_end].copy()
    return train, valid, holdout


def prepare(d):
    d = d.copy()
    d["SignalDate"] = pd.to_datetime(d["SignalDate"], errors="coerce")
    for c in ["Entry", "Stop", "ATR20Pct", "SetupScore"] + list(BIN_SPECS):
        if c in d.columns:
            d[c] = pd.to_numeric(d[c], errors="coerce")
    d["Risk"] = (d["Entry"] - d["Stop"]).abs()
    return d


def stats(g, target_r):
    n = len(g)
    if n == 0:
        return {"N": 0, "SuccessRate": np.nan, "ExpectancyR": np.nan}
    p = float(g["Outcome"].mean())
    return {"N": n, "SuccessRate": p, "ExpectancyR": p * (1 + target_r) - 1.0}


def main():
    path = ROOT / "data" / "training_signals.parquet"
    d = prepare(pd.read_parquet(path))
    if d.empty:
        raise ValueError("No training signals")

    # Precomputed outcome labels for each signal are not enough for alternate
    # targets/horizons, so V8 expects the extended outcome parquet generated by
    # scripts/edge_discovery_v8_outcomes.py.
    out = ROOT / "artifacts" / "edge_discovery_v8"
    out.mkdir(parents=True, exist_ok=True)

    outcome_path = ROOT / "data" / "edge_discovery_v8_outcomes.parquet"
    if not outcome_path.exists():
        raise FileNotFoundError(outcome_path)

    outcomes = pd.read_parquet(outcome_path)
    outcomes["SignalDate"] = pd.to_datetime(outcomes["SignalDate"], errors="coerce")
    outcomes = outcomes.dropna(subset=["SignalDate"])

    keys = [
        "Ticker", "SignalDate", "Direction", "Setup", "SetupScore",
        "RVOL20", "BreakoutATR", "ATRCompression", "Trend20", "Trend50",
        "Trend200", "RS_SPY_20", "TR_ATR20", "CloseLocation",
        "BaseRangePct", "ATR20Pct", "RiskATR", "GapPct"
    ]
    key_cols = [c for c in keys if c in d.columns]
    base = d[key_cols].drop_duplicates(["Ticker", "SignalDate", "Direction", "Setup"])
    outcomes = outcomes.merge(
        base, on=["Ticker", "SignalDate", "Direction", "Setup"], how="left"
    )

    train, valid, holdout = split_by_date(outcomes)
    outcome_cols = {"Outcome", "TargetR", "HorizonDays"}
    missing = outcome_cols - set(outcomes.columns)
    if missing:
        raise ValueError(f"Missing outcome columns: {sorted(missing)}")

    pair_rows = []
    for direction in ["Long", "Short"]:
        vdir = valid[valid["Direction"] == direction]
        hdir = holdout[holdout["Direction"] == direction]
        for setup in sorted(vdir["Setup"].dropna().unique()):
            vs = vdir[vdir["Setup"] == setup]
            hs = hdir[hdir["Setup"] == setup]
            for feature, bins in BIN_SPECS.items():
                if feature not in vs.columns:
                    continue
                vb = pd.cut(vs[feature], bins=bins, include_lowest=True)
                hb = pd.cut(hs[feature], bins=bins, include_lowest=True)
                for label in vb.dropna().unique():
                    vg = vs[vb == label]
                    if len(vg) < MIN_VALIDATION_N:
                        continue
                    hg = hs[hb == label]
                    for horizon in HORIZONS:
                        for target_r in TARGETS:
                            vsub = vg[(vg["HorizonDays"] == horizon) & (vg["TargetR"] == target_r)]
                            hsub = hg[(hg["HorizonDays"] == horizon) & (hg["TargetR"] == target_r)]
                            if len(vsub) < MIN_VALIDATION_N:
                                continue
                            sv = stats(vsub, target_r)
                            sh = stats(hsub, target_r)
                            pair_rows.append({
                                "Direction": direction,
                                "Setup": setup,
                                "Feature": feature,
                                "Bin": str(label),
                                "HorizonDays": horizon,
                                "TargetR": target_r,
                                "Validation_n": sv["N"],
                                "Validation_success_rate": sv["SuccessRate"],
                                "Validation_expectancy_R": sv["ExpectancyR"],
                                "Holdout_n": sh["N"],
                                "Holdout_success_rate": sh["SuccessRate"],
                                "Holdout_expectancy_R": sh["ExpectancyR"],
                            })

    pair = pd.DataFrame(pair_rows)
    if pair.empty:
        raise RuntimeError("No candidate rules met the minimum validation sample size")

    # Rank discovery rules only within the validation sample.
    candidates = pair.sort_values(
        ["Validation_expectancy_R", "Validation_success_rate", "Validation_n"],
        ascending=[False, False, False]
    ).head(30)

    # Robust candidate test: holdout must preserve positive expectancy and have
    # at least 50 observations. This is a report, not a tuning loop.
    confirmed = candidates.copy()
    confirmed["HoldoutPass"] = (
        (confirmed["Holdout_n"] >= 50) &
        (confirmed["Holdout_expectancy_R"] > 0)
    )

    meta = {
        "signals_input": int(len(d)),
        "outcome_rows": int(len(outcomes)),
        "train_signals": int(len(train)),
        "validation_rows": int(len(valid)),
        "holdout_rows": int(len(holdout)),
        "target_grid_R": TARGETS,
        "horizons_days": HORIZONS,
        "minimum_validation_n": MIN_VALIDATION_N,
        "minimum_holdout_n_for_pass": 50,
        "discovery_rule": "setup x feature-bin x horizon x target, ranked by validation expectancy",
        "holdout_rule": "exact discovered condition confirmed without retuning; positive holdout expectancy and N>=50",
        "note": "10-year current-universe backtest remains survivorship-biased; this workflow is for research discovery only.",
    }
    pair.to_csv(out / "all_candidate_rules.csv", index=False)
    candidates.to_csv(out / "top30_validation_candidates.csv", index=False)
    confirmed.to_csv(out / "top30_holdout_confirmation.csv", index=False)
    (out / "summary.json").write_text(json.dumps(meta, indent=2))
    print(json.dumps(meta, indent=2))
    print("\nTOP VALIDATION CANDIDATES")
    print(candidates.to_string(index=False))
    print("\nHOLDOUT CONFIRMATION")
    print(confirmed.to_string(index=False))


if __name__ == "__main__":
    main()
